name: expirochain_app
description: "EXPIROCHAIN - Medicine Lifecycle & Expiry Management Platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  path_provider: ^2.1.2
  flutter:
    sdk: flutter

  # Networking & Storage
  dio: ^5.9.0
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8
  file_picker: ^8.0.0

  # iOS style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

# ---------------- ICON CONFIG ----------------
flutter_launcher_icons:
  android: true
  ios: false
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  image_path: "assets/icon/app_icon.png"


# ---------------- FLUTTER CONFIG ----------------
flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png
